// Build the course-card icon set → writes `icons.js` (window.LU_ICONS = { name: innerSVG }).
//
// Icons come from icons0.dev's backend (Iconify): https://api.iconify.design/<collection>/<name>.svg
// (`@icons0/<collection>/<name>` ⇒ Iconify `<collection>:<name>`). We use the **lucide** line set,
// strip each glyph's inline stroke/fill attrs so the card's `.ring svg` CSS governs colour + weight,
// and inline the geometry into icons.js (a plain <script> the card loads synchronously — no fetch
// race during headless screenshotting). Re-run after editing ICONS:  node build-icons.mjs
import { writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));

// One distinctive lucide glyph per course topic (referenced by cardgen's slug→icon map).
const ICONS = [
  'blocks', 'images', 'brain', 'wrench', 'git-branch',        // ADK track
  'refresh-cw', 'shapes', 'book-open', 'workflow', 'plug',     // Studio track …
  'mic', 'share-2', 'shield-check', 'scale', 'flask-conical',
  'trending-up', 'rocket', 'activity', 'package',
  'drafting-compass',                                          // Architect
  'bot', 'cpu', 'database', 'gauge',                           // modules
  'users', 'megaphone', 'handshake', 'shopping-cart', 'banknote', 'target', // functions
  'hammer', 'code', 'briefcase',                               // legacy
  'flow',                                                      // legacy fallback (node-graph, hand-rolled below)
];

// A couple of glyphs we keep hand-rolled (matches the original card's node-graph mark).
const HANDROLLED = {
  flow: '<circle cx="6" cy="6" r="2.2"/><circle cx="6" cy="18" r="2.2"/><circle cx="18" cy="12" r="2.2"/><path d="M8.1 6.8c4 .6 5.2 2.3 7.5 4.3M8.1 17.2c4-.6 5.2-2.3 7.5-4.3"/>',
};

const stripAttrs = (s) => s
  .replace(/<svg[^>]*>/i, '').replace(/<\/svg>/i, '')
  .replace(/\s(fill|stroke|stroke-width|stroke-linecap|stroke-linejoin)="[^"]*"/g, '')
  .replace(/\s+/g, ' ').trim();

const out = {};
for (const name of ICONS) {
  if (HANDROLLED[name]) { out[name] = HANDROLLED[name]; continue; }
  const url = `https://api.iconify.design/lucide/${name}.svg`;
  const res = await fetch(url);
  if (!res.ok) { console.error(`MISS ${name} (${res.status})`); continue; }
  const svg = await res.text();
  const inner = stripAttrs(svg);
  if (!inner || /error/i.test(svg)) { console.error(`EMPTY ${name}`); continue; }
  out[name] = inner;
  console.log(`ok  ${name}`);
}

const body = `// AUTO-GENERATED by build-icons.mjs — lucide glyphs (via icons0.dev/Iconify), inline-stroke stripped.\n`
  + `window.LU_ICONS = ${JSON.stringify(out, null, 0)};\n`;
writeFileSync(join(HERE, 'icons.js'), body);
console.log(`\nwrote icons.js — ${Object.keys(out).length} icons`);
